const sidebar = {
  "/base/engine/": [
    "1.index",
    "1.utils",
    "2.project",
    "3.vuecli",
    "4.env",
    "5.ui",
    "6.layout",
    "7.single",
    "8.page",
    "9.module",
    "10.skill",
    "11.mock",
    "12.optimization",
    "13.deploy",
  ],
  "/base/project/": [
    "1.index",
    "1.config",
    "2.skill",
    "3.login",
    "4.projectMonitor",
    "5.test",
    "6.configurePrem",
    "7.internationalization",
    "8.errorCollection",
    "9.optimize",
    "10.server",
    "11.pwa",
    "12.upload",
    "13.video",
  ],
  "/base/vue2.x/": [
    "1.index",
    "1.vue-cli",
    "2.vue-base",
    "2.vue-message",
    "2.vue-directive",
    "2.vue-lifecycle",
    "2.vue-error",
    "3.vue-router",
    "4.vuex",
    "5.ui",
    "6.utils",
    "7.style",
    "8.eslint",
  ],
  "/senior/1.micro/": [
    "1.index",
    "1.singlespa",
    "1.singlespa2",
    "2.qiankun",
    "2.qiankun2",
    "3.share",
    "4.dev",
  ],
  "/senior/2.deploy/": [
    "1.index",
    "1.local",
    "2.gitlab",
    "3.genkins",
    "4.centos",
    "5.nginx",
  ],
  "/senior/3.component/": [
    "1.index",
    "1.button",
    "2.dropdown",
    "3.form",
    "4.input",
    "5.checkBox",
    "6.cascader",
    "7.date",
    "8.dispaly",
    "9.dynamics",
    "1.env",
    "10.tree",
    "12.table",
    "1.recursion",
    "3.dialog",
    "4.render",
    "9.alert",
    "13.publish",
  ],
  "/source/vue-cli2.x/": ["1.index"],
  "/source/vue2.x/": [
    "1.index",
    "1.entry",
    "2.initMixin",
    "3.stateMixin",
    "4.eventsMixin",
    "5.lifecycleMixin",
    "6.renderMixin",
    "7.initGlobalAPI",
    "8.mount",
    "9.ast",
    "10.optimize",
    "11.gencode",
    "12.mount",
    "13._render",
    "14._update",
  ],
  "/source/vue-router3.x/": ["1.index", "2.origin"],
  "/source/vuex3.x/": ["1.index", "2.use", "3.origin"],
  "/source/vue-cli3.x/": ["1.index"],
};
module.exports = sidebar;
