const sidebar = {
    '/base/engine/': [
        '1.index',
        '1.utils',
        '2.project',
        '3.vuecli',
        '4.env',
        '5.ui',
        '6.layout',
        '7.single',
        '8.page',
        '9.module',
        '10.skill',
        '11.mock',
        '12.optimization',
        '13.deploy'
    ],
    '/base/project/': [
        '1.index',
        '1.config',
        '2.skill',
        '3.login',
        '4.projectMonitor',
        '5.test',
        '6.configurePrem',
        '7.internationalization',
        '8.errorCollection',
        '9.optimize',
        '10.server',
        '11.pwa',
        '12.upload',
        // '13.video'
    ],
    '/base/vue2.x/': [
        '1.index',
        '1.vue-cli',
        '2.vue',
        '2.message',
        '2.directive',
        '2.vue3',
        '2.vue4',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.utils',
        '7.style',
        '8.eslint',
    ],
    '/base/vue3.x/': [
        '1.index',
        '1.vue-cli3',
        '2.vue',
        '2.vue1',
        '3.vue-router',
        '4.vuex',
        '5.ui',
        '6.vueuse'
    ],
    '/senior/1.micro/': [
        '1.index',
        '1.singlespa',
        '1.singlespa2',
        '2.qiankun',
        '2.qiankun2',
        '3.share',
        '4.dev'
    ],
    '/senior/2.typescript/': [
        '1.index',
        '1.env',
        '2.base',
        '3.deduction',
        '4.type',
        '5.class',
        '6.interface',
        '7.generic',
        '8.compatible',
        '9.protect',
        '10.infer',
        '11.overlapping',
        '12.condition',
        '13.builtin',
        '14.package',
        '15.custom',
        '16.unknown',
        '17.module',
        '18.statement',
        '19.extend'
    ],
    '/senior/3.deploy/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/4.component/': [
        '1.index',
        '1.button',
        '2.dropdown',
        '3.form',
        '4.input',
        '5.checkBox',
        '6.cascader',
        '7.date',
        '8.dispaly',
        '9.dynamics',
        '1.env',
        '10.tree',
        '12.table',
        '1.recursion',
        '3.dialog',
        '4.render',
        '9.alert',
        '13.publish',
    ],
    '/senior/vue3/': [
        '1.index',
    ],
    '/source/vue-cli2.x/': [
        '1.index'
    ],
    '/source/vue2.x/': [
        '1.index',
        '2.initGlobalAPI',
        '3.initMixin',
        '4.stateMixin',
        '5.eventsMixin',
        '6.lifecycleMixin',
        '7.renderMixin',
        '8.mount',
        '9.ast',
        '10.optimize',
        '11.gencode',
        '12.mount',
        '13._render',
        '14._update'
    ],
    '/source/vue-router3.x/': [
        '1.index',
        '2.origin'
    ],
    '/source/vuex3.x/': [
        '1.index',
        '2.use',
        '3.origin'
    ],
    '/source/vue-cli3.x/': [
        '1.index',
    ],
    '/source/vue3.x/': [
        '1.index',
        '2.initGlobalAPI',
        '3.initMixin',
        '4.stateMixin',
        '5.eventsMixin',
        '6.lifecycleMixin',
        '7.renderMixin',
        '8.mount',
        '9.ast',
        '10.optimize',
        '11.gencode',
        '12.mount',
        '13._render',
        '14._update'
    ],
    '/source/vue-router4.x/': [
        '1.index'
    ],
    '/source/vuex4.x/': [
        '1.index'
    ]
}
module.exports = sidebar