const sidebar = {
  "/base/engine/": [
    "1.index",
    "1.utils",
    "2.project",
    "3.vuecli",
    "4.env",
    "5.ui",
    "6.layout",
    "7.single",
    "8.page",
    "9.module",
    "10.skill",
    "11.mock",
    "12.optimization",
    "13.code",
    "14.deploy",
  ],
  "/base/project/": [
    "1.index",
    "1.micro",
    "2.message",
    "3.login",
    "4.monitor",
    "5.test",
    "6.prem",
    "7.language",
    "8.file",
    "9.skeleton",
    "10.ssr",
    "11.pwa",
    "12.upload",
    "13.video",
    "14.map",
    "15.rich",
    "16.export",
    "17.image",
    "18.lazy",
    "19.dragger",
    "20.mobile",
    "21.scroll"
  ],
  "/base/vue2.x/": [
    "1.index",
    "1.vue-cli",
    "2.vue-base",
    "2.vue-message",
    "2.vue-directive",
    "2.vue-lifecycle",
    "2.vue-transition",
    "2.vue-component",
    "2.vue-render",
    "3.vue-router",
    "4.vuex",
    "5.ui",
    "6.utils",
    "7.style",
    "8.eslint",
  ],
  "/senior/1.mobile/": [
    "1.index",
    "1.local",
    "2.gitlab",
    "3.genkins",
    "4.centos",
    "5.nginx",
  ],
  "/senior/2.browser/": [
    "1.index",
    "1.local",
    "2.gitlab",
    "3.genkins",
    "4.centos",
    "5.nginx",
  ],
  "/senior/3.component/": [
    "1.index",
    "1.button",
    "2.dropdown",
    "3.form",
    "4.input",
    "5.checkBox",
    "6.cascader",
    "7.date",
    "8.dispaly",
    "9.dynamics",
    "1.env",
    "10.tree",
    "3.table",
    "3.fitimg",
    "3.textoverflow",
    "3.texttyper",
    "1.recursion",
    "3.dialog",
    "9.alert",
    "13.publish",
  ],
  "/source/vue-cli2.x/": [
    "1.index",
    "2.myVueCli"
  ],
  "/source/vue2.x/": [
    "1.index",
    "2.project",
    "3.vue",
    "4.init",
    "5.merge",
    "6.state",
    "7.mount",
    "8.mount",
    "9.ast",
    "10.optimize",
    "11.gencode",
    "12.watcher",
    "13.render",
    "14.component",
    "15.element",
    "16._update",
    "17.createComponent",
    "18.patchVnode",
  ],
  "/source/1.micro/": [
    "1.index",
    "1.singlespa",
    "1.singlespa2",
    "2.qiankun",
    "2.qiankun2",
    "3.share",
    "4.dev",
  ],
  "/source/vue-router3.x/": [
    "1.index",
    "2.origin",
    "3.link",
    "4.view"
  ],
  "/source/vuex3.x/": [
    "1.index",
    "2.use",
    "3.origin"
  ],
  "/source/vue-cli3.x/": [
    "1.index"
  ],
};
module.exports = sidebar;
